site_name: My Docs
theme:
  name: material

  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
  # カラーパレットの設定
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/
  # フォントの設定
  font:
    text: Roboto
    code: Roboto Mono

  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/
  # 言語の設定
  language: ja

  features:
    - navigation.tabs

markdown_extensions:
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
